### ISSUE TITLE
Add all proving artifacts / files to frontend

### ISSUE THREAD

**Issue by vb7401** [jubmoji/jubmoji.quest#14]
We should host as many of the necessary artifacts for proving (.wasm, .vkey, .zkey) as possible to avoid another fetch from another server.

**Comment by vb7401** [comment]
- [ ] Benchmark page load times with and without loading the artifacts
- [ ] Benchmark loading the artifacts from external servers

**Comment by AndrewCLu** [comment]
Pending: https://github.com/project-vinyl/babyjubjub-ecdsa/issues/10
