### ISSUE TITLE
FE missing components & refinements  

### ISSUE THREAD

**Issue by kalidiagne** [jubmoji/jubmoji.quest#42]
- [x] Update Tailwind config with correct colors  (https://github.com/project-vinyl/jubmoji.quest/pull/43)
- [x] Onboarding modal with steps 
- [x] Rename `Options` component for `Filters` to match the behaviour  https://github.com/jubmoji/jubmoji.quest/issues/73
- [x] Add `PowerCard` component (https://github.com/project-vinyl/jubmoji.quest/pull/43)
- [x] Add `Leaderboard` component
- [x] Add missing details for `CollectionCard` https://github.com/jubmoji/jubmoji.quest/issues/73
- [x] Add `BackupModal` component

**Comment by vb7401** [comment]
@kalidiagne can this issue be updated?

**Comment by kalidiagne** [comment]
Can close after https://github.com/jubmoji/jubmoji.quest/issues/73

**Comment by kalidiagne** [comment]
@vb7401 this one is done
