### ISSUE TITLE
Replace `crypto.randomUUID` for Safari

### ISSUE THREAD

**Issue by vb7401** [jubmoji/jubmoji.quest#47]
Getting this error when using Safari on MacOS, need to replace UUID 

```
Unhandled Runtime Error
TypeError: crypto.randomUUID is not a function. (In 'crypto.randomUUID()', 'crypto.randomUUID' is undefined)
```

**Comment by AndrewCLu** [comment]
@vb7401 I wasn't able to reproduce this on my machine. We should test this in people's safari mobile browsers
